---
title: "logistic_regression"
author: "Eduardo Carrasco"
date: "2/7/2017"
output: html_document
---

```{r setup}
setwd('/Users/lalo/CodingComplication/DataScienceProjects/Statistical_Learning_In_R/Logistic_Regression/')
```

## R Markdown

```{r Library}
library(aod)
library(ggplot2)
library(Rcpp)
```

## Including Plots

You can also embed plots, for example:

```{r Load the data}
gre_scores <- read.csv("http://www.ats.ucla.edu/stat/data/binary.csv")
## view the first few rows of the data
head(gre_scores)

summary(gre_scores)

sapply(gre_scores, sd)


```

```{r first regression}
xtabs(~ admit + rank, data = gre_scores)

gre_scores$rank <- factor(gre_scores$rank)
mylogit <- glm(admit ~ gre + gpa + rank, data = gre_scores, family = "binomial")

summary(mylogit)
```

```{r Summrizing}
confint(mylogit)

confint.default(mylogit)
wald.test(b = coef(mylogit), Sigma = vcov(mylogit), Terms = 4:6)

```

```{r Redue Wald Test}
l <- cbind(0,0,0,1,-1,0)
wald.test(b = coef(mylogit), Sigma = vcov(mylogit), L = l)
## Odds Response
exp(coef(mylogit))
## odds ratios and 95% CI
exp(cbind(OR = coef(mylogit), confint(mylogit)))


```

```{r Reformate wit New Data}
gre_scores_with_mean <- with(gre_scores,
  data.frame(gre = mean(gre), gpa = mean(gpa), rank = factor(1:4)))

## view data frame
gre_scores_with_mean

gre_scores_with_mean$rankP <- predict(mylogit, gre_scores_with_mean = gre_scores_with_mean, type = "response")
gre_scores_with_mean
## http://www.ats.ucla.edu/stat/r/dae/logit.htm

newdata2 <- with(gre_scores, data.frame(gre = rep(seq(from = 200, to = 800, length.out = 100), 4), gpa = mean(gpa), rank = factor(rep(1:4, each = 100))))


newdata3 <- cbind(newdata2, predict(mylogit, gre_scores_with_mean = newdata2, type="link", se=TRUE))
head(newdata)

ggplot(newdata3, aes(x = gre, y = PredictedProb)) + geom_ribbon(aes(fill = rank), alpha = .2) + geom_line(aes(colour = rank), size=1)

```
