---
title: "Intermediate_Support_Vector_Machines"
author: "Eduardo Carrasco"
date: "3/8/2017"
output: html_document
---

```{r setup, include=FALSE}
setwd("/Users/lalo/CodingComplication/DataScienceProjects/Statistical_Learning_In_R/Support_Vector_Machines")
library(e1071)
library(ROCR)
```

```{r The Set up}
set.seed(1)
x=matrix(rnorm(200*2), ncol=2)
x[1:100,]=x[1:100,]+2
x[101:150,]=x[101:150,]-2
y=c(rep(1,150), rep(2,50))
svm_data = data.frame(x=x, y=as.factor(y))
plot(x, col=y)
```

```{r Train the Data}
train = sample(200, 100)
svmfit = svm(y~., data=svm_data[train, ], kernel="radial", gamma=1, cost=1)
plot(svmfit, svm_data[train,])
```

```{r summary}
summary(svmfit)
svmfit2 = svm(y~., data=svm_data[train, ], kernel="radial", gamma=1, cost=1e5)
plot(svmfit2,  svm_data[train,])
#Cross validation
set.seed(1)
tune.out = tune(svm, y~., data = svm_data[train, ], kernerl="radical", ranges = list(cost=c(0.1, 1, 10, 100, 100), gamma=c(0.5, 1, 2, 3, 4)))
summary(tune.out)
table(true=svm_data[train, "y"], pred=predict(tune.out$best.model, newdata = svm_data[-train,]))
```

```{r ROC Curves}
rocplot = function(pred, truth, ...){
  predob = prediction(pred,truth)
  perf = performance(predob, "tpr", "fpr")
  plot(perf,...)
}
```

```{r get some work done}
cat('\014')
svmfit.opt = svm(y~., data = svm_data[train, ], kernel="radial", gamma=2, cost=1, decision.values=T)
fitted=attributes(predict(svmfit.opt, svm_data[train, ], decision.values=TRUE))$decision.values
par(mfrow=c(1,2))
rocplot(fitted, svm_data[train, "y"], main="Training Data")
svm.fit.flex = svm(y~., data = svm_data[train,], kernel="radial", gamma=50, cost=1, decision.values=T)
new.fitted = attributes(predict(svm.fit.flex, svm_data[train,], decision.values=T))$decision.values
rocplot(fitted, svm_data[train, "y"], add=T, col="red")
fitted=attributes(predict(svmfit.opt, svm_data[-train,], decision.values = T))$decision.values
rocplot(fitted, svm_data[-train, "y"], main="Test Data")
rocplot(fitted, svm_data[-train, "y"], add=T, col="blue")
```

```{r Multi-Class SVM}
set.seed(1)
x=rbind(x, matrix(rnorm(50*2), ncol=2))
y=c(y, rep(0,50))
x[y==0, 2]= x[y==0,2]+2
final_data = data.frame(x=x, y=as.factor(y))
par(mfrow=c(1,1))
plot(x, col=(y+1))
svmfit3 = svm(y~., data = final_data, kernel="radial", cost=10, gamma=1)
plot(svmfit3, final_data)
```
